### ISSUE TITLE
php7 & volumes

### ISSUE THREAD

**Issue by thiesschneider** [rubenv/docker-ttrss-plugins#2]
Hey,

thanks for your docker container!
Do you plan to upgrade to php7?
And is there an option to make the plugins and themes path availible as a volume?

thx!

**Comment by rubenv** [comment]
I'm not sure ttrss supports php7. Wasn't the case last time I tried it.

Why do you want it upgraded?

---

As for plugins:

Just mount your own folders into it with `-v`: `-v /path/to/my/plugins:/var/www/plugins`. That should override it.

**Comment by lasat** [comment]
Current container is alreadey using php7. Issue could be closed #7

**Comment by rubenv** [comment]
@lasat Thanks!
