### ISSUE TITLE
UTF8MB4 encoding in config.php

### ISSUE THREAD

**Issue by WangQiru** [rubenv/docker-ttrss-plugins#3]
Hi Ruben,

Can you add ENV for MYSQL_CHARSET in config.php?

**Comment by rubenv** [comment]
Mind sending a pull request?

**Comment by WangQiru** [comment]
Hi , I tried adding `ENV MYSQL_CHARSET utf8mb4` to Dockerfile line 35 and adding `$config['MYSQL_CHARSET'] = env('MYSQL_CHARSET', 'utf8mb4');` to configure-db.php line 54, able to build but unable to access when running.

I'm new to docker, anything wrong?

**Comment by rubenv** [comment]
I'm sorry, I'm not a MySQL user, so I'm afraid I can't help you out there.

What does that variable even do? Can't you just configure your database to use the right charset?

**Comment by WangQiru** [comment]
It defines the charset used by ttrss, the default is UTF8 and in mysql only UTF8MB4 provides full support for unicode (emoji, Chinese, Japanese etc.) [See this](https://mathiasbynens.be/notes/mysql-utf8mb4#databases-tables-columns) [this](https://tt-rss.org/forum/viewtopic.php?t=3721) and [this](https://tt-rss.org/forum/viewtopic.php?t=3820)

I've been using ttrss with mysql for years, it's hard for me to switch now. I'm configuring it manually via sh into container now.
